Examenv4/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('apps.app_examen.urls')),
    url(r'media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/app_examen/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
	url(r'^$',login,{'template_name':'app_examen/index.html'}, name='login'),
	url(r'^logout/$', logout_then_login, name='logout'),
	url(r'^$',index_view,name='index_view'),
	url(r'^registro_materia/$',registro_materia.as_view(),name='registro_materia'),
	url(r'^registro_maestro/$',registro_maestro.as_view(),name='registro_maestro'),
	url(r'^listado_materias/$',listado_materias,name='listado_materias'),
	url(r'^registro_alumno/$',registro_alumno.as_view(),name='registro_alumno'),
	url(r'^detalle_materia/(?P<pk>[-\w]+)/$',detalle_materia,name='detalle_materia'),
	url(r'^anadir_pregunta/(?P<pk>[-\w]+)/$',anadir_pregunta,name='anadir_pregunta'),
	url(r'^generar_examen/(?P<pk>[-\w]+)/$',generar_examen,name='crear_examen'),
	url(r'^anadir_respuesta/$',anadir_respuesta,name='anadir_respuesta'),
	url(r'^materias_alumno/$',materias_alumno,name='materias_alumno'),
	url(r'^detalle_examen/(?P<pk>[-\w]+)/$',detalle_examen,name='detalle_examen'),
	url(r'^realizar_examen/(?P<pk>[-\w]+)/$',realizar_examene,name='realizar_examen'),
	url(r'^calificaciones/$',calificaciones,name='calificaciones'),
	url(r'^detalle_calificacion/(?P<pk>[-\w]+)/$',detalle_calificacion,name='detalle_calificacion'),
	url(r'^lista_calificaciones/(?P<pk>[-\w]+)/$',lista_calificaciones,name='lista_calificaciones'),




	
	#url(r'^examen_lista/$',examen_lista,name='examen_lista'),

]

apps/app_examen/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator,MaxValueValidator
from django.utils import timezone
from multiselectfield import MultiSelectField
import datetime

# Create your models here.
class maestro(models.Model):
	user_perfil = models.OneToOneField(User, related_name="profile")
	n_empleado = models.CharField(max_length=64,primary_key=True)
	nombre = models.CharField(max_length=64)
	correo = models.EmailField()
	categoria = models.CharField(max_length=64,null = True,default="maestros")

	def __unicode__(self):
		return '%s'%(self.n_empleado)

class materia(models.Model):
	serie = models.SlugField(max_length=64, primary_key=True)#forzar al usuario a capyurarlo de una manera expresion regular
	nombre = models.CharField(max_length=64,blank=False)
	maestro_a = models.ForeignKey(maestro, max_length=64,related_name='maestro_inparte')
	#periodo = models.CharField(max_length=64)
	def __unicode__(self):
		return '%s  %s'%(self.serie,self.nombre)

class alumno(models.Model):
	user_perfil = models.OneToOneField(User, related_name="alumno")
	n_control = models.CharField(max_length=8,primary_key=True)
	nombre = models.CharField(max_length=64)
	apellido = models.CharField(max_length=64)
	correo = models.EmailField()
	categoria = models.CharField(max_length=64,default="estudiante")

	def __unicode__(self):
		return '%s'%(self.n_control)

class alumno_materia(models.Model):
	id = models.AutoField(primary_key=True)
	alum = models.ForeignKey(alumno,related_name='alumno')# numero de control
	materi = models.ForeignKey(materia,related_name='materia')#serie de materia

	def __unicode__(self):
		return '%s'%(self.id)

	class Meta:
		unique_together = ('alum','materi')



class pregunta(models.Model):
	id = models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=64)
	materia = models.ForeignKey(materia,related_name="mat")
	semestre = models.IntegerField()
	nivel = (('Facil','Facil'),('Intermedio','Intermedio'),('Dificil','Dificil'))
	dificultad = models.CharField(max_length=64,choices=nivel)
	valor = models.PositiveIntegerField( validators=[MinValueValidator(1),MaxValueValidator(100)])

	def __unicode__(self):
		return '%s'%(self.nombre)

	def __str__(self):
		return '%s'%(self.id)

class respuesta(models.Model):
	id = models.AutoField(primary_key=True)
	pregun = models.ForeignKey(pregunta,related_name="pregunt")
	nombre = models.CharField(max_length=64)
	correcta = models.BooleanField()
	terminar = models.BooleanField(default=False)

	def __unicode__(self):
		return u"%s"%(self.nombre)

	def __str__(self):
		return u'%s'%(self.id)

class pregunta_respuesta(models.Model):
	id_pregunta_respuesta = models.AutoField(primary_key=True)
	id_pregunta = models.ForeignKey(pregunta)
	id_respuesta = models.ManyToManyField(respuesta)

	def __unicode__(self):
		return u'%s %s'%(self.id_pregunta_respuesta,self.id_pregunta)

	def get_pregunta(self):
		return "\n".join([p.nombre for p in self.id_pregunta.all()])

	def get_respuesta(self):
		return "\n".join([p.nombre for p in self.id_respuesta.all()])

class examen(models.Model):
	id_examen = models.AutoField(primary_key=True)
	id_materia = models.ForeignKey(materia,related_name="idmate")
	id_alumno = models.ForeignKey(alumno,null=True,blank=True)
	unidad = models.IntegerField()
	id_pregunta_respuesta = models.ManyToManyField(pregunta_respuesta)

	def __unicode__(self):
		return '%s'%(self.id_examen)

	def get_pregunta_respuesta(self):
		return "\n".join([str(p.id_pregunta_respuesta) for p in self.id_pregunta_respuesta.all()])

	class Meta:
		unique_together = ('id_materia','unidad')



class realizar_examen(models.Model):
	id = models.AutoField(primary_key=True)
	id_alumno = models.ForeignKey(alumno)
	id_examen = models.ForeignKey(examen,null=True,blank=True)
	id_pregunta_respuesta = models.ManyToManyField(pregunta_respuesta,blank=True,null=True)
	id_respuesta = models.ManyToManyField(respuesta,blank=True,null=True)
	puntuacion = models.IntegerField(blank=True,null=True)
	unidad = models.IntegerField(blank=True,null=True)
	id_materia = models.ForeignKey(materia,blank=True,null=True)
	done = models.BooleanField(default=False)

	def __unicode__(self):
		return '%s'%(self.id)

	def get_pregunta_respuesta(self):
		return "\n".join([str(p.id_pregunta_respuesta) for p in self.id_pregunta_respuesta.all()])

	def get_respuesta(self):
		return "\n".join([p.nombre for p in self.id_respuesta.all()])

	def add_to_score(self,points):
		self.current_score += int(points)
		self.save()

	@property
	def get_current_score(self):
		return self.current_score

apps/app_examen/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.views.generic import FormView, CreateView, ListView,DetailView,UpdateView,DeleteView
from .forms import UserForm, estudianteForm, materiaForm, alumno_materiaForm, preguntaForm, respuestaForm, pregunta_respuestaForm, examenForm, realizar_examenForm
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import realizar_examen, maestro, materia, alumno, alumno_materia, pregunta, respuesta, pregunta_respuesta, examen
from django.core.paginator import Paginator, EmptyPage, InvalidPage, PageNotAnInteger
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.models import User
from django.views.generic.edit import ModelFormMixin
from decimal import Decimal  
# Create your views here.

def index_view(request):
	return render(request,'app_examen/index.html')

class registro_maestro(FormView):
	template_name = 'app_examen/registro_maestro.html'
	form_class = UserForm
	success_url = reverse_lazy('index_view')

	def form_valid(self,form):
		user = form.save()
		p = maestro()
		p.user_perfil = user
		p.n_empleado = form.cleaned_data['n_empleado']
		p.nombre = form.cleaned_data['nombre']
		p.correo = form.cleaned_data['correo']
		p.save()
		return super(registro_maestro,self).form_valid(form)

class registro_alumno(FormView):
	template_name = 'app_examen/registro_alumno.html'
	form_class = estudianteForm
	success_url = reverse_lazy('index_view')

	def form_valid(self,form):
		user = form.save()
		p = alumno()
		p.user_perfil = user
		p.n_control = form.cleaned_data['n_control']
		p.nombre = form.cleaned_data['nombre']
		p.apellido = form.cleaned_data['apellido']
		p.correo = form.cleaned_data['correo']
		p.save()
		return super(registro_alumno,self).form_valid(form)

def listado_materias(request):
	current_user = request.user.profile.n_empleado
	materias = materia.objects.filter(maestro_a = current_user)
	ctx = {'materias':materias,}
	return render(request,'app_examen/listado_materias.html',ctx)

#def registro_materia(request):
	#instace_maestro = get_object_or_404(maestro,n_empleado="cafj940201hbclls09")
#	profe = maestro.objects.get(n_empleado = request.POST['maestro_a'])
#	form=materiaForm(request.POST or None)
#	ctx = {
#		"form":form
#	}
#	if form.is_valid:
#		instace = form.save(commit=False)
#		instace.maestro_a = profe
#		instace.save()
#		return redirect('registro_materia')

#	return render(request,'app_examen/registro_materia.html',ctx)

class registro_materia(CreateView):
	template_name = 'app_examen/registro_materia.html'
	model = materia
	fields = ['serie','nombre','maestro_a']
	success_url = reverse_lazy('index_view')

	def post(self, request, *args, **kwargs):
		flag = False
		p = materia()
		query = materia.objects.filter(serie = request.POST['serie'])
		if query:
			if query.count == 1:
				flag = False
		else:
			a = request.POST['maestro_a']
			user = maestro.objects.get(n_empleado=a)
			print user
			p.serie = request.POST['serie']
			p.nombre = request.POST['nombre']
			p.maestro_a = user
			p.save()

		return redirect('index_view')

def detalle_materia(request,pk):
	insta = get_object_or_404(materia,serie=pk)
	ctx = {"object":insta}
	form = alumno_materiaForm(request.POST or None)
	try:
		if form.is_valid():
			instance = form.save(commit=False)
			instance.alum = alumno.objects.get(n_control = request.POST['alum'])
			instance.materi = materia.objects.get(serie = request.POST['materi'])
			instance.save()
			return redirect('index_view')
	except:
			print "error"
	return render(request,'app_examen/detalle_materia.html',ctx)

def anadir_pregunta(request,pk=None):
	insta = get_object_or_404(materia,serie=pk)
	ctx = {"object":insta}
	form = preguntaForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.materia = materia.objects.get(serie = request.POST['materia'])
		instance.save()
		return redirect('anadir_respuesta')
		#return render_to_response('anadir_respuesta/pregunta_get')

	return render(request,'app_examen/anadir_pregunta.html',ctx)

def anadir_respuesta(request,pk=None):
	pregunta_get = pregunta.objects.latest('id')
	respuesta_get = respuesta.objects.latest('id')
	form = respuestaForm(request.POST or None)
	form2 = pregunta_respuestaForm(request.POST or None)
	all_res = respuesta.objects.filter(pregun=pregunta_get)
	lista4 = []
	for i in all_res:
		lista4.append(i)

	print lista4

	if form.is_valid():
		instance = form.save(commit=False)
		instance.pregun = pregunta.objects.get(id=request.POST['pregun'])
		instance.nombre = request.POST['nombre']
		instance.save()
		#################################################################
		if instance.terminar == True:
			p = pregunta_respuesta()
			p.id_pregunta = instance.pregun
			p.save()
			p.id_respuesta =  lista4
			return redirect('index_view')
		
	else:
		print 'error en captura de pregunta'
	return render(request,'app_examen/respuesta.html',{"object":pregunta_get})


def generar_examen(request,pk):
	form = examenForm(request.POST or None)
	insta = get_object_or_404(materia,serie=pk)
	pregunta_res = pregunta_respuesta.objects.all()
	ctx = {
		'object':insta,
		'pregunta_res':pregunta_res,
		'form':form,
	}

	context = {}
	print pregunta_res
	if 'id_respuesta' in request.GET:
		context['id_respuesta'] = request.GET.get('id_respuesta')
		return context
		#print context

	i = 0
	for i in context.items():
		i += 1
		#print i 
		return i
	
	if form.is_valid():
		instance = form.save()
		instance.id_materia = materia.objects.get(serie = request.POST['id_materia'])
		#instance.id_pregunta_respuesta = pregunta_respuesta.objects.get(id_pregunta_respuesta=request.POST['id_pregunta_respuesta']).values()
		#print instance.id_pregunta_respuesta
		instance.save()
	return render(request,'app_examen/crear_examen.html',ctx)

def materias_alumno(request):
	current_user = request.user.alumno.n_control
	a_m = alumno_materia.objects.filter(alum = current_user)
	ctx = {'a_m':a_m,}
	#print a_m
	return render(request,'app_examen/materias_alumno.html',ctx)

def detalle_examen(request,pk=None):
	insta = get_object_or_404(materia,serie=pk)
	current_user = request.user.alumno.n_control
	queryset_list = examen.objects.all()
	queryset_list2 = alumno_materia.objects.filter(alum = current_user)
	queryset_list3 = realizar_examen.objects.all()
	ctx = {
		"object":insta,
		"object_list": queryset_list,
		"object_list2":queryset_list2,
		"object_list3":queryset_list3,
	}
	return render(request,'app_examen/detalle_examen.html',ctx)


def realizar_examene(request,pk=None):
	insta = get_object_or_404(examen,id_examen=pk)
	current_user = request.user.alumno.n_control
	queryset_list = examen.objects.filter(id_examen = insta.id_examen)
	queryset_list2 = realizar_examen.objects.filter(id_examen = insta.id_examen)
	queryset_list3 = realizar_examen.objects.filter(id_examen= insta.id_examen)
	form = realizar_examenForm(request.POST or None)
	guess = request.POST.get('id_respuesta')
    #is_correct = self.question.check_if_correct(guess)
    
	#print guess
	ctx = {
		"object":insta,
		"object_list": queryset_list,
		"object_list2":queryset_list2,
		"object_list3":queryset_list3,
		"form":form,
	}
	context = {}
	if 'id_respuesta' in request.GET:
		context['id_respuesta'] = request.GET.get('id_respuesta')
	context['id_respuesta'] = request.GET.get('id_respuesta')

	r_corectas = respuesta.objects.filter(correcta = True)
	lista = []
	lista2 = []
	lista3= []
	for i in r_corectas:
		lista.append(i.id)
	respuestas = realizar_examen.objects.filter(id_examen=pk)
	if form.is_valid():
		instance = form.save()
		
		for l in request.POST.getlist('id_respuesta'):
			lista2.append(int(l))
		#verifica que los respuestas del examen que se contextto sean correctas
		for l in lista:
			if l in lista2:
				lista3.append(l)

		total_res = float(len(lista2)*10)#primeo
		aciertos = float(len(lista3)*10)#segundo
		promedio = float(((aciertos/total_res)*.100)*1000)
		#print float(promedio)
		#print total_res
		#print aciertos
		instance.puntuacion = float(promedio)
		instance.done = True
		instance.save()


		return redirect('index_view')

	return render(request,'app_examen/realizar_examen.html',ctx)


#ojo cambiar la parte de las preguntas que compare las preguntas que hay como la logitud

def calificaciones(request):
	current_user = request.user.alumno.n_control
	a_m = alumno_materia.objects.filter(alum = current_user)
	ex = realizar_examen.objects.filter(id_alumno=current_user)
	ctx = {'a_m':a_m,'ex':ex}
	return render(request,'app_examen/calificaciones.html',ctx)

def detalle_calificacion(request,pk=None):
	current_user = request.user.alumno.n_control
	mate = get_object_or_404(materia,serie=pk)
	a_m = alumno_materia.objects.filter(alum = current_user)
	ex = realizar_examen.objects.filter(id_alumno=current_user)
	ctx = {'a_m':a_m,'ex':ex,'object':mate}
	return render(request,'app_examen/detalle_calificaciones.html',ctx)

def lista_calificaciones(request,pk=None):
	current_user = request.user.profile.n_empleado
	mate = get_object_or_404(materia,serie=pk)
	#a_m = alumno_materia.objects.filter(alum = current_user)
	ex = realizar_examen.objects.filter(id_materia=mate.serie)
	ctx = {'ex':ex,'object':mate}
	return render(request,'app_examen/lista_calificaciones.html',ctx)

templates/app_examen/anadir_pregunta.html
{% extends 'base.html' %}
{% load staticfiles %}
{%block content %}
<style type="text/css">
#login-page {
   width: 500px;
}

.card {
     position: absolute;
     left: 50%;
     top: 50%;
     -moz-transform: translate(-50%, -50%)
     -webkit-transform: translate(-50%, -50%)
     -ms-transform: translate(-50%, -50%)
     -o-transform: translate(-50%, -50%)
     transform: translate(-50%, -50%);
}
</style>
<div id="login-page" class="row">
	<center><h5>Ingrese una pregunta</h5></center>
      <div class="col s12 z-depth-6 card-panel">
		<form  action="."  method="POST" enctype="multipart/form-data">
			{% csrf_token %}
	          <div class="row">
	          </div>

	          <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="nombre" id="id_nombre">
		              <label for="nombre">Nombre</label>
	            </div>
          	  </div>

          	  <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="materia" id="id_materia" value="{{object.serie}}">
		              <label for="materia">Materia</label>
	            </div>
          	  </div>

          	  <div class="row">
          	  	<div class="input-field col s12">
				    <select  name="semestre" id="id_semestre">
				      <option value="" disabled selected>Choose your option</option>
				      <option value="1">1</option>
				      <option value="2">2</option>
				      <option value="3">3</option>
				      <option value="4">4</option>
				      <option value="5">5</option>
				      <option value="6">6</option>
				      <option value="7">7</option>
				      <option value="8">8</option>
				      <option value="9">9</option>
				    </select>
				    <label>semestre</label>
				</div>
          	  </div>

          	  <div class="row">
          	  	<div class="input-field col s12">
				    <select name="dificultad" id="id_dificultad">
				      <option value="" disabled selected>Choose your option</option>
				      <option value="Facil">Facil</option>
				      <option value="Intermedio">Intermedio</option>
				      <option value="Dificil">Dificil</option>
				    </select>
				    <label>Dificultad</label>
				</div>
          	  </div>

          	  <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="valor" id="id_valor">
		              <label for="valor">Valor</label>
	            </div>
          	  </div>

          	  <div class="row">
		            <button class="btn waves-effect waves-light col s12" type="submit" name="action" id="boton-guardar" name="boton-guardar">Registrar
		            </button>
          	  </div>
		</form>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
	            $('#boton-guardar').click(function(){
	                
	                var pregunta = document.getElementById("id_nombre").value;
	               
	                localStorage.setItem("Pregunta", pregunta);
	                
	             });
	        });
	    </script>
</div>
{%endblock%}

templates/app_examen/pregunta.html
{% extends 'base.html' %}
{% load staticfiles %}
{%block content %}
<style type="text/css">
#login-page {
   width: 500px;
}

.card {
     position: absolute;
     left: 50%;
     top: 50%;
     -moz-transform: translate(-50%, -50%)
     -webkit-transform: translate(-50%, -50%)
     -ms-transform: translate(-50%, -50%)
     -o-transform: translate(-50%, -50%)
     transform: translate(-50%, -50%);
}
</style>
<div id="login-page" class="row">
	<center><h5>Ingrese una pregunta</h5></center>
      <div class="col s12 z-depth-6 card-panel">
		<form  action="."  method="POST" enctype="multipart/form-data">
			{% csrf_token %}
	          <div class="row">
	          </div>

	          <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="nombre" id="id_nombre">
		              <label for="nombre">Nombre</label>
	            </div>
          	  </div>

          	  <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="materia" id="id_materia">
		              <label for="materia">Materia</label>
	            </div>
          	  </div>

          	  <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="semestre" id="id_semestre">
		              <label for="semestre">Semestre</label>
	            </div>
          	  </div>

          	  <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="dificultad" id="id_dificultad">
		              <label for="dificultad">Dificultad</label>
	            </div>
          	  </div>

          	  <div class="row">
	            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="valor" id="id_valor">
		              <label for="valor">Valor</label>
	            </div>
          	  </div>

          	  <div class="row">
		            <button class="btn waves-effect waves-light col s12" type="submit" name="action">Registrar
		            </button>
          	  </div>
          	  
		</form>
	</div>
</div>
{%endblock%}

templates/app_examen/registro_alumno.html
{% load staticfiles %}
{%block content %}
<script src="{% static 'materialize/js/jquery-2.2.1.js'%}"> </script>
<link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css'%}">
<script src="{% static 'materialize/js/materialize.min.js'%}"> </script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style type="text/css">
  body {
    height: 100%;
}
html {
    display: table;
    margin: auto;Username

}
body {
    display: table-cell;
    vertical-align: middle;
    background: #4ECDC4;
}

#login-page {
   width: 500px;
}

.card {
     position: absolute;
     left: 50%;
     top: 50%;
     -moz-transform: translate(-50%, -50%)
     -webkit-transform: translate(-50%, -50%)
     -ms-transform: translate(-50%, -50%)
     -o-transform: translate(-50%, -50%)
     transform: translate(-50%, -50%);
}
</style>
<br>
<br>
<body>
  <div id="login-page" class="row">
      <div class="col s12 z-depth-6 card-panel">
        <form id="miForm" action="."  method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
          </div>

          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">person_outline</i>
              <input class="validate"  type="text" name="username" id="id_username">
              <label for="email" data-error="wrong" data-success="right">Username</label>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">lock_outline</i>
              <input class="validate" type="password" name="password1" id="id_password">
              <label for="password">Password</label>
            </div>
          </div>

           <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">lock_outline</i>
              <input class="validate" type="password" name="password2" id="id_password2">
              <label for="password2">Password confirm</label>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">lock_outline</i>
              <input class="validate" type="text" name="n_control" id="id_n_control">
              <label for="n_control">Numero de control</label>
            </div>
          </div>

           <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">lock_outline</i>
              <input class="validate" type="text" name="nombre" id="id_nombre">
              <label for="nombre">Nombre</label>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">lock_outline</i>
              <input class="validate" type="text" name="apellido" id="id_apellido">
              <label for="apellido">Apellido</label>
            </div>
          </div>

           <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">mail_outline</i>
              <input class="validate" type="text" name="correo" id="id_correo">
              <label for="correo">Correo</label>
            </div>
          </div>



          <div class="row">
            <button class="btn waves-effect waves-light col s12" type="submit" name="action" id="login">Registrarse
            </button>
          </div>

          <div class="row">
            <div class="input-field col s6 m6 l6">
              <p class="margin medium-small"><a href="/">Login</a></p>
            </div>
            <!--<div class="input-field col s6 m6 l6">
                <p class="margin right-align medium-small"><a href="#">Forgot password?</a></p>
            </div>-->         
          </div>

        </form>
      </div>
  </div> 
</body>
</html>
{% endblock %}

templates/app_examen/registro_materia.html
{% extends 'base.html' %}
{% load staticfiles %}
{%block content %}
<center><h3>Registra una materia</h3></center>
	 <div id="login-page" class="row">
	 	<div class="col s12 z-depth-6 card-panel">
	 		 <form id="miForm" action="."  method="POST" enctype="multipart/form-data">
	 		 	{% csrf_token %}
	 		 	<div class="row">
		            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="serie" id="id_serie">
		              <label for="serie" data-error="wrong" data-success="right">Serie</label>
		            </div>
	            </div>
	            <div class="row">
		            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="nombre" id="id_nombre">
		              <label for="nombre" data-error="wrong" data-success="right">Nombre</label>
		            </div>
	            </div>
	            <div class="row">
		            <div class="input-field col s12">
		              <i class="material-icons prefix">person_outline</i>
		              <input class="validate"  type="text" name="maestro_a" id="id_maestro_a" value="{{user.profile.n_empleado}}">
		              <label for="maestro_a" data-error="wrong" data-success="right">Maestro</label>
		            </div>
	            </div>
		           
	            <div class="row">
		            <button class="btn waves-effect waves-light col s12" type="submit" name="action">Registrar
		            </button>
          		</div>
	 		 </form>
	 	</div>
	 </div>
<style type="text/css">
#login-page {
   width: 500px;
}

.card {
     position: absolute;
     left: 50%;
     top: 50%;
     -moz-transform: translate(-50%, -50%)
     -webkit-transform: translate(-50%, -50%)
     -ms-transform: translate(-50%, -50%)
     -o-transform: translate(-50%, -50%)
     transform: translate(-50%, -50%);
}
</style>
{% endblock %}